### ISSUE TITLE
Front page design optimisation.

### ISSUE THREAD

**Issue by ashfiles** [ashfiles/AshDevOps.com#4]
Initially we thought of only placing a portrait image of the person on left and a brief intro at right, but now we want to integrate a self explanatory video "Who I Am" at the home page such as when anyone opens the website, they can see the image , short description as well as the video on the very first page without scrolling such as the video doesn't feel very pushy.

**Comment by Nandini1071** [comment]
Ok I got your issue

**Comment by Nandini1071** [comment]
Will clone the repo and will check the code

**Comment by ashfiles** [comment]
> Will clone the repo and will check the code

Thanks 😊

**Comment by ashfiles** [comment]
Sure, a zoom call would save our time in explanation.

**Comment by ashfiles** [comment]
> We can discuss on this by tomorrow about the changes


Sure, a zoom call would save our time in explanation.
Please feel free to connect via email at newemailsite@gmail.com for further planning.

**Comment by Nandini1071** [comment]
I checked the code and I think you can directly use about page in to home page by adding the code, so will clone the repo and will make the required changes and you can check and let me know any changes if required.

**Comment by Nandini1071** [comment]
And also second thing is you are css and js in the same file which you can use in different files which makes things clear and there are many changes which you can do in this project.

**Comment by Nandini1071** [comment]
Please let me know your suggestion on this @ashfiles

**Comment by ashfiles** [comment]
> I checked the code and I think you can directly use about page in to home page by adding the code, so will clone the repo and will make the required changes and you can check and let me know any changes if required.

Please no, if we integrate the about page in the home page, then the home page will become too long, for this reason we are going with multiple page design instead of a single page-multiple scroll design. For this reason we have to integrate only a single video in home page.

**Comment by Nandini1071** [comment]
Which video you want to integrate?

**Comment by ashfiles** [comment]
> Which video you want to integrate?

You can use this one: https://www.youtube.com/watch?v=xk4XIdrr30M

**Comment by ashfiles** [comment]
> And also second thing is you are css and js in the same file which you can use in different files which makes things clear and there are many changes which you can do in this project.

Please suggest more changes.

**Comment by Nandini1071** [comment]
> > And also second thing is you are css and js in the same file which you can use in different files which makes things clear and there are many changes which you can do in this project.
> 
> Please suggest more changes.

what changes I mean first I want to understand about your project is this a portfolio one ?

**Comment by Nandini1071** [comment]
> > Which video you want to integrate?
> 
> You can use this one: https://www.youtube.com/watch?v=xk4XIdrr30M

You want to merge this video in home page ?

**Comment by Nandini1071** [comment]
Hi, please let me know your suggestion on this so that will start developing the page.

**Comment by ashfiles** [comment]
> Hi, please let me know your suggestion on this so that will start developing the page.

Let’s discuss this in more detail over a Zoom or Hangout session. Please let me know when you’re available. Thanks!

**Comment by Nandini1071** [comment]
> > Hi, please let me know your suggestion on this so that will start developing the page.
> 
> Let’s discuss this in more detail over a Zoom or Hangout session. Please let me know when you’re available. Thanks!

Actually I am working professional so we can discuss the requirement here itself not sure about the availability. Thanks

**Comment by Nandini1071** [comment]
You can elaborate what all things required for this project in bullet points will check and let you know my suggestions on that and then would start contributing on the same.

**Comment by ashfiles** [comment]
Understood. I’ll proceed with using AI for this task. Thank you for your input.

**Comment by ashfiles** [comment]
> You can elaborate what all things required for this project in bullet points will check and let you know my suggestions on that and then would start contributing on the same.

Understood. I’ll proceed with using AI for this task. Thank you for your input.

**Comment by ashfiles** [comment]
Added video section "A Brief Introduction" above the "Quick Links" section.
